Update run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -2,8 +2,8 @@ name: Run Data Center Monitor
 
 on:
   schedule:
-    - cron: '0 * * * *'  # co godzinę
-  workflow_dispatch:     # pozwala uruchomić ręcznie
+    - cron: '0 * * * *'
+  workflow_dispatch:
 
 jobs:
   run-script:
@@ -27,6 +27,13 @@ jobs:
           EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
           WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
         run: python main.py
+
+      - name: Check output file exists
+        run: |
+          echo "--- FILES IN FOLDER ---"
+          ls -la
+          echo "--- FILE INFO ---"
+          file data_center_monitoring.xlsx || echo "Excel not found"
 
       - name: Commit output file
         env:
