Update run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -2,7 +2,7 @@ name: Run Data Center Monitor
 
 on:
   schedule:
-    - cron: '0 * * * *'  # co godzinę
+    - cron: "0 * * * *"  # co godzinę
   workflow_dispatch:
 
 jobs:
@@ -26,24 +26,19 @@ jobs:
           EMAIL_USER: ${{ secrets.EMAIL_USER }}
           EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
           WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
-        run: python main.py
+        run: python main_larget_datacenter.py
 
-      - name: Check output file exists
+      - name: Commit output file exists
         run: |
           echo "--- FILES IN FOLDER ---"
           ls -la
           echo "--- FILE INFO ---"
-          file data_center_monitoring.xlsx || echo "Excel not found"
+          file data_center_monitoring.csv || echo "Excel not found"
 
       - name: Commit output file
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git config --global user.name "github-actions"
-          git config --global user.email "actions@github.com"
-          git pull origin main --rebase || true
-          git add data_center_monitoring.xlsx data_center_monitoring.csv projekty_wg_kraju.png projekty_wg_miesiaca.png || true
-          git status
-          git diff --cached --quiet && echo "No changes to commit" || \
-            (git commit -m "Update XLSX/CSV/Charts [auto]" && \
-             git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || true)
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add data_center_monitoring.csv projekty_wg_*.png || true
+          git commit -m "Auto update monitoring data [skip ci]" || echo "No changes"
+          git push
